---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Siyao Jiang"
date: "09 18 2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
library(Lahman)
dim(Teams)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2

```{r}
mets <- Teams  |> 
  dplyr::filter(teamID == "NYN")
my_mets <- mets |> 
  dplyr::filter(yearID %in% 2004:2012) |> 
  dplyr::select(yearID,G,W,L)
my_mets
```

### Exercise 3

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, RA, RS=R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

### Exercise 4

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate( WPct = W/G )
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct_hat = 1 / (1 + (RA/RS)^2))
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct_hat * G )
mets_ben
```

### Exercise 5

```{r}
dplyr::filter(mets_ben, W >= W_hat)
```

```{r}
dplyr::filter(mets_ben, W < W_hat)
```

### Exercise 6

```{r}
dplyr::arrange(mets_ben, desc(WPct))
```

### Exercise 7

### Exercise 8

...

### Exercise 9

...

### Exercise 10

...
